### ISSUE TITLE
[USERSNAP] Hi GovTools team, there is no vote button available for me to vote for this latest Governance Action proposal. Please fix this for me so that I can actually vote :) Also, your link to "help" goes to a support page that doesn't exist.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2313] opened 2024-11-02 18:07 UTC
**Taken at**: https://gov.tools/connected/governance_actions/51f495aa23f4b3b3aa90afde4a0e67823bb7ac4ac65f5ffbb138373b863f2f74#0
**Fields**:
- Add a comment: Hi GovTools team, there is no vote button available for me to vote for this latest Governance Action proposal. Please fix this for me so that I can actually vote :)

Also, your link to &#34;help&#34; goes to a support page that doesn&#39;t exist.

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1920x1080
**[Open #156 in Usersnap](https://app.usersnap.com/l/feedback/0adec254-5210-4341-9350-57a1a9414e24?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-11-04 15:22
According to [CIP-1694 bootstrapping phase part](https://github.com/cardano-foundation/CIPs/blob/master/CIP-1694/README.md#bootstrapping-phase), it is said that _"a vote from the constitutional committee is sufficient to change the protocol parameters"_. This should have been more explicit.
Therefore vote totals and options will be adjusted for bootstrapping and full governance phases accordingly #2316 .
In regards to help button pointing to the link that doesnt "work", its a duplicate of #2292 .

**Closed by bosko-m** 2024-11-04 15:22 UTC
Labels: usersnap-bug
