### ISSUE TITLE
Dashboard - Styling

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1277] opened 2024-06-13 10:01 UTC
## Context & versions
https://dev.gov.tools/proposal_discussion

## Steps to reproduce

  1. Click on Dashboard
 

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/2fc81091-0961-468c-9d2c-dabfc7f379fb)

## Expected behavior

- Search bar is too big

**Comment by m-i-k-e** [comment] 2024-06-13 12:45
This design in Figma is here: https://www.figma.com/design/239JKpjintphf2Go5NPipp/Proposal-discussion-Forum?node-id=948-42255&t=Ta2djbq6ulbHEgSI-1

**Comment by m-i-k-e** [comment] 2024-06-13 12:51
Please follow the filter/search pattern exactly as implemented on GovTool. https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=7842-115617&t=pV7sEwa70lcq8C6W-1

**Comment by ValMBO** [comment] 2024-06-14 13:17
This is the updated bug filed: https://github.com/orgs/IntersectMBO/projects/30/views/10?pane=issue&itemId=67463241

**Comment by bosko-m** [comment] 2024-07-03 09:10
Closing as duplicate of https://github.com/IntersectMBO/govtool/issues/1297

**Closed by bosko-m** 2024-07-03 09:10 UTC
Labels: UX, PDF Bug
