### ISSUE TITLE
🐛 Accepts dRep Registration with Mismatched Anchor URL and Registration Data

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1862] opened 2024-08-29 09:12 UTC
### Area

Other

### Domain

preview.gov.tools

### Context

When attempting to register a dRep with a valid field entered, but with an anchor URL that does not exactly match the registration data, the system currently accepts the registration without displaying the error message: `Your External Data Does Not Match the Original File.` Instead, the registration proceeds successfully, and the dRep information displayed includes the data from the anchor URL.

### Steps to reproduce

1. Connect your wallet.
2. Navigate to the dRep registration section.
3. Fill in the valid registration data and proceed.
4. Enter an anchor URL with information that differs from the dRep registration data. 
5. Observe the transaction process.
6. Review the registered dRep information.

### Actual behavior

The system accepts the dRep registration despite the mismatch between the anchor URL and the registration data.

![image](https://github.com/user-attachments/assets/2ee68543-80f0-4101-9805-31f48d2d01c5)

Anchor URL: https://metadata.cardanoapi.io/data/dRep
Registration Data:
Hello.jsonId 
```
{
  "@context": {
    "CIP100": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md#",
    "CIP119": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0119/README.md#",
    "hashAlgorithm": "CIP100:hashAlgorithm",
    "body": {
      "@id": "CIP119:body",
      "@context": {
        "references": {
          "@id": "CIP119:references",
          "@container": "@set",
          "@context": {
            "GovernanceMetadata": "CIP100:GovernanceMetadataReference",
            "Identity": "CIP100:IdentityReference",
            "Link": "CIP100:LinkReference",
            "Other": "CIP100:OtherReference",
            "label": "CIP100:reference-label",
            "uri": "CIP100:reference-uri",
            "referenceHash": {
              "@id": "CIP119:referenceHash",
              "@context": {
                "hashDigest": "CIP119:hashDigest",
                "hashAlgorithm": "CIP100:hashAlgorithm"
              }
            }
          }
        },
        "paymentAddress": "CIP119:paymentAddress",
        "givenName": "CIP119:givenName",
        "image": "CIP119:image",
        "objectives": "CIP119:objectives",
        "motivations": "CIP119:motivations",
        "qualifications": "CIP119:qualifications",
        "doNotList": "CIP119:doNotList"
      }
    },
    "authors": {
      "@id": "CIP100:authors",
      "@container": "@set",
      "@context": {
        "name": "http://xmlns.com/foaf/0.1/name",
        "witness": {
          "@id": "CIP100:witness",
          "@context": {
            "witnessAlgorithm": "CIP100:witnessAlgorithm",
            "publicKey": "CIP100:publicKey",
            "signature": "CIP100:signature"
          }
        }
      }
    }
  },
  "authors": [],
  "hashAlgorithm": "blake2b-256",
  "body": {
    "givenName": "Hello ",
    "motivations": "test",
    "objectives": "test",
    "paymentAddress": "addr_test1qqk7c8nvx7yeutsuhgj92lulfnc6cyest4vdmycn9z077t3pmhhpdhdmyvqysl53q3387ruud46klus49vs7acxdpunshlrgcl",
    "qualifications": "test",
    "references": [
      {
        "@type": "Other",
        "label": "Label",
        "uri": "test.com"
      }
    ]
  }
}
```

Preview dRep Info Post-Registration:

![image](https://github.com/user-attachments/assets/76cf4e44-1ea9-42e3-92e6-938a7e80dcbe)

### Expected behavior

An error message should be displayed indicating that the external data does not match the original file, preventing the registration from proceeding.
  ![image](https://github.com/user-attachments/assets/7196d41d-1dc6-4459-be13-87ed1f44e61e)

**Comment by MSzalowski** [comment] 2024-08-30 12:46
I can't reproduce that - could you please provide more info from the network tab for the /validate request?

**Comment by kneerose** [comment] 2024-08-30 13:36
@MSzalowski It can no longer be reproduced. It seems your changes have resolved the issue.

**Comment by bosko-m** [comment] 2024-09-02 08:16
Closing as per the comment above.

**Closed by bosko-m** 2024-09-02 08:16 UTC
Labels: 🐛 Bug, Other area
