### ISSUE TITLE
[USERSNAP] Cannot vote on https://gov.tools/connected/governance_actions/59fd353253eb177e2104e8f23ea4c63e3d32ef95c7865d03e90d3884424dc1db#0 using Yoroi hardware wallet. "Error: unexpectedly missing governance action id"

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2069] opened 2024-09-19 16:06 UTC
**Taken at**: https://gov.tools/connected/governance_actions/59fd353253eb177e2104e8f23ea4c63e3d32ef95c7865d03e90d3884424dc1db#0
**Fields**:
- Add a comment: Cannot vote on https://gov.tools/connected/governance_actions/59fd353253eb177e2104e8f23ea4c63e3d32ef95c7865d03e90d3884424dc1db#0 using Yoroi hardware wallet.
&#34;Error: unexpectedly missing governance action id&#34;

**Browser**: Chrome 128 (Linux)
**Screen size**: 2560x1440
**[Open #131 in Usersnap](https://app.usersnap.com/l/feedback/86da5643-f47a-4426-a101-53f80a1aa00a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment] 2024-09-20 08:17
Forwarded to Yoroi team

**Comment by Ryun1** [comment] 2024-09-20 08:29
duplicate of https://github.com/IntersectMBO/govtool/issues/2068

**Closed by Ryun1** 2024-09-20 08:29 UTC
Labels: usersnap-bug
