### ISSUE TITLE
[BUG] Submit Button Non-Functional on Submit Proposal as a Governance Action

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1466] opened 2024-07-04 08:11 UTC
## Context & versions
- When I try to submit my proposal by navigating through the proposal ID or refreshing the proposal details page, the submit button is not functional, preventing me from submitting the proposal as a governance action.

## Steps to reproduce
- Create a proposal.
- Refresh the proposal details page Or navigate through the page using URL
- Attempt to submit the proposal as a governance action.

https://www.loom.com/share/d3b5b96a518641da9ed4256703ab1651?sid=05ecb344-45cd-4ed8-aaf1-b2dbd67bb8c6

## Actual behaviour
- The submit button is clickable but does not trigger any action. An error is displayed in the console.
![Screenshot from 2024-07-04 10-07-12](https://github.com/IntersectMBO/govtool/assets/49801844/5c38e305-21ab-46fe-9d66-9473647e9718)

**Comment by kneerose** [comment] 2024-07-04 13:33
@bosko-m, have you tried refreshing the proposal details page and submitting it as a governance action?
- This video will clarify it for you better


https://www.loom.com/share/425c1f96877240ee9998d713433c6d5d?sid=dafd1ad7-9522-41b0-9c3a-6e50c91b6285

**Comment by spannercode** [comment] 2024-07-04 13:35
To reproduce the issue, refreshing the proposal page is important which causes the re-verification of the identity. Without refreshing the page, the issue does not occur on the normal flow.

**Comment by vpaunovic** [comment] 2024-07-04 14:04
@kneerose @spannercode We worked on that `signData` modal now on refresh, because it was doing that on the deployed version but locally it does not happen. So we worked on that thing, and hopefully, that will sort out that on the deployed version too. We will inform you when it is available in new version.

CC: @teske00

**Comment by vpaunovic** [comment] 2024-07-04 14:42
@kneerose @spannercode It is available in v.0.2.5..  It will be available on dev-sancho as soon as guys import it and redeploy it.

CC: @bosko-m @teske00

**Comment by pmbinapps** [comment] 2024-07-05 14:46
@bosko-m this is currently not working on test-sancho. Works fine on dev-sancho and beta. 

On test following error msg is shown when Submit is clicked:

![image](https://github.com/IntersectMBO/govtool/assets/82152577/8f246d5f-21b0-4c00-8be5-9e54f0532cbb)

To reproduce:
Make GA with following data:
![image](https://github.com/IntersectMBO/govtool/assets/82152577/ff29b7ab-7b08-47c9-8afa-2ac1cdafb60f)

Link #1: https://test.com

Use json:
https://raw.githubusercontent.com/pmbinapps/vva/main/tmp/data.jsonld

**Comment by vpaunovic** [comment] 2024-07-08 07:19
@bosko-m @kneerose It can be tested on the latest Sancho-dev and closed everything is okay.

CC: @teske00

**Comment by kneerose** [comment] 2024-07-08 09:19
I have tested this on both the test and dev environments on Sanchonet, and it does not reproduce anymore.

**Comment by bosko-m** [comment] 2024-07-09 11:37
Thanks @kneerose .
@vpaunovic Will be closed once its released to Sancho (Beta).

**Comment by vpaunovic** [comment] 2024-07-09 13:42
@bosko-m Isn't it already on beta?

**Comment by kneerose** [comment] 2024-08-08 09:40
I have tested this on both the test and dev environments on Sanchonet, and it no longer reproduces.

This issue can be closed now.  
CC: @bosko-m"

**Comment by bosko-m** [comment] 2024-08-08 18:25
Closing as per the comment above.

**Closed by bosko-m** 2024-08-08 18:25 UTC
Labels: 🐛 Bug, PDF Bug
