### ISSUE TITLE
[USERSNAP] search? works for the ID, snd not the name?

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2317] opened 2024-11-03 09:58 UTC
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Add a comment: search? works for the ID, snd not the name?

**Browser**: Chrome 130 (macOS Catalina)
**Screen size**: 1280x800
**[Open #157 in Usersnap](https://app.usersnap.com/l/feedback/b70a1815-e594-47b1-b02a-d93c68706820?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-11-04 14:04
Duplicate of #1893 .

**Closed by bosko-m** 2024-11-04 14:04 UTC
Labels: usersnap-bug
