### ISSUE TITLE
[USERSNAP] I'm unable to get my anchor link to be accepted.  I have downloaded from step one.  Added to github on main branch, copy paste URL from nav bar into field 3 and get Does not match error?

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1694] opened 2024-08-07 13:30 UTC
**Sender**: jonah@kochfoto.com
**Taken at**: https://preview.gov.tools/register_drep
**Fields**:
- Add a comment: I&#39;m unable to get my anchor link to be accepted.  I have downloaded from step one.  Added to github on main branch, copy paste URL from nav bar into field 3 and get Does not match error?

**Browser**: Chrome 123 (macOS Catalina)
**Screen size**: 1465x796
**[Open #96 in Usersnap](https://app.usersnap.com/l/feedback/fa1c498c-4c82-4254-a1dd-1e4610cca585?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by MSzalowski** [comment] 2024-08-07 13:32
I believe it is caused by not passing the raw metadata content, but instead link to the file inside the repostitory

**Comment by MSzalowski** [comment] 2024-08-07 13:49
Closing as https://github.com/IntersectMBO/govtool/issues/1696

**Closed by MSzalowski** 2024-08-07 13:49 UTC
Labels: usersnap-bug
