### ISSUE TITLE
🐛 [TEST_STACK] Wrong protocol version in dbsync

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#2275] opened 2024-10-30 07:11 UTC
### Area

Other

### Domain

Custom setup

### Context

I was trying to setup my test govtool env using latest dbsync docker image 
- https://github.com/intersectmbo/cardano-db-sync/pkgs/container/cardano-db-sync/294118289?tag=13.6.0.0-pre

### Actual behavior

- Dbsync is sync with latest node 
- latest Protocol version is 9

### Expected behavior

- Dbsync is sync with latest node 
- latest Protocol version is 10

**Comment by bosko-m** [comment] 2024-11-03 18:23
Where are you getting wrong protocol version from @kneerose ?

**Comment by kneerose** [comment] 2024-11-05 04:37
The test environment we have setup for govtool in Sancho is available at https://govtool.cardanoapi.io/. However, it currently returns a major protocol version of 9. For API details, https://govtool.cardanoapi.io/api/epoch/params.

**Comment by bosko-m** [comment] 2024-11-05 09:03
@kneerose Is that your node running or its from Intersect?

**Comment by mesudip** [comment] 2024-11-05 10:13
The issue was seen when using:
**Node version:** ghcr.io/intersectmbo/cardano-node:10.1.1-pre
**Dbsync version:** ghcr.io/intersectmbo/cardano-db-sync:13.6.0.0-pre


> Is that your node running or its from Intersect?

We are managing the deployment on a server provided by Intersect.
We also tried locally and same issue was reproduced.

We have decided to downgrade the node and dbsync (WIP).

**Comment by mesudip** [comment] 2024-11-06 11:10
The update was re-tested on **Sanchonet** with following results
- node-10.1.2 , dbsync-13.5.0.2 (wrong protocol version)
- node 10.1.2, dbsync-13.6.0.0-pre  (wrong protocol version)

**Comment by Ryun1** [comment] 2024-11-06 19:53
@mesudip do you think this is a deployment/environment issue OR a DBSync issue/bug?

due to it not happening on PreProd id guess its a deployment/environment issue

**Comment by bosko-m** [comment] 2024-11-07 08:00
Should we close this one @mesudip ?

**Closed** 2024-11-13 21:19 UTC
Labels: 🐛 Bug, Other area
