### ISSUE TITLE
[BUG] Support Incompatible Wallets

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1141] opened 2024-06-03 01:59 UTC
## Context & versions
- The "connect wallet" popup modal currently displays incompatible wallets, meaning wallets that are not listed on the following compatibility list: https://docs.sanchogov.tools/how-to-use-the-govtool/getting-started/get-a-compatible-wallet. 

## Steps to reproduce
- Install a wallet extension that does not support CIP-95 or is not listed on the compatibility [list](https://docs.sanchogov.tools/how-to-use-the-govtool/getting-started/get-a-compatible-wallet) .
- Click the "connect wallet" button.
- Observe the available wallet options.
- Attempt to connect with the incompatible wallet.

## Actual behaviour
- The popup modal displays both compatible and incompatible wallets, as shown in the attached images:

![image](https://github.com/IntersectMBO/govtool/assets/49801844/3b9e01fc-4962-441e-b126-d376ed69195b)

- Attempting to connect with an incompatible wallet results in the 'undefined reading getExtensions' error.

![image (1)](https://github.com/IntersectMBO/govtool/assets/49801844/ff9f8187-bd22-406a-bebf-f5019c67ba43)

## Expected behaviour
- Should verify CIP-95 compatibility before displaying any wallets.

For more details, refer to this [report](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/10/#behaviors/82cf9472ef278cecbfd40a28e08d3f79/b88133985aaff207/)

**Comment by MSzalowski** [comment] 2024-06-14 08:05
@Ryun1 What  do you think of filtering out CIP-95 incompatible wallets?

**Comment by MSzalowski** [comment] 2024-06-14 11:50
After a more  in-depth analysis, the issue is rather on the wallet side.
We display on a list every wallet that includes:
```typescript
supportedExtensions: [{ cip: 95 }]
```
and the wallet you provided on a picture, indeed includes this entry in its declaration:
![Zrzut ekranu z 2024-06-14 13-13-50](https://github.com/IntersectMBO/govtool/assets/24510246/2f1f4b0e-d0fd-421b-95f9-ad9972471296)

And that makes, that we, based on [CIP-95 Extension API](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0095#governance-extension-api), provide the `extensions: [{ cip: 95 }]` argument while enabling the wallet. And at this step there is the problem described in the issue - `priority` wallet even though it declares support for CIP-95, it doesn't really have such support that is why such error on modal occurs.

However, I made some improvement to the listing of the wallets and displaying an error on a modal informing the user, that the wallet that has been listed doesn't really have the CIP-95 support or even CIP-30 support  due to missing `getExtensions` described [here](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#initial-api).


@Ryun1 Should we depend only on [the list of compatible wallets](https://docs.sanchogov.tools/how-to-use-the-govtool/getting-started/get-a-compatible-wallet) and display only these? Or on the `choose wallet modal`
should we display every wallet that has the `cip-95` and `cip-30` supported extension or the wallets that has only the `cip-95` extension as we do currently?

So far within [this PR](https://github.com/IntersectMBO/govtool/pull/1293) I introduced following solution:
![Nagranie ekranu z 2024-06-14 13-38-24](https://github.com/IntersectMBO/govtool/assets/24510246/aeb03d9a-0ae2-4beb-a809-b9979125c59f)

**Comment by bosko-m** [comment] 2024-07-03 09:28
Closing this with the discussion above.

**Closed by bosko-m** 2024-07-03 09:28 UTC
Labels: 🐛 Bug
