### ISSUE TITLE
4D: For first access of GA ' only governance actions I can see are the ones that have been accepted by the Constitutional Committee'

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/govtool#21] opened 2023-12-15 15:50 UTC
4D: As any user of the app

When I view the governance actions page, the default setting for the filter that tells me if the governance action has bEn accepted by the Constitutional CommittE or not is set to show me those governance actions which have already bEn accepted

So that I do not waste my time looking at governance actions that will not pass.

**Comment by l-br1** [comment] 2024-05-08 10:45
In theory this flow is not needed as voting of cc and DReps happens at the same time

**Comment by Ryun1** [comment] 2024-08-07 15:11
duplicate of https://github.com/IntersectMBO/govtool/issues/19

**Closed by Ryun1** 2024-08-07 15:11 UTC
Labels: ⚙ Backend
