### ISSUE TITLE
[USERSNAP] Add comma's next to Vote Numbers

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2083] opened 2024-09-26 15:01 UTC
**Taken at**: https://gov.tools/connected/governance_actions/15f82a365bdee483a4b03873a40d3829cc88c048ff3703e11bd01dd9e035c916#0
**Fields**:
- Name of the idea or new feature: Add comma&#39;s next to Vote Numbers
- Please summarize your idea or new feature: Under &#34;Votes Submitted for this governance action&#34; add commas to easily read the Yes, Abstain, and No numbers. I&#39;d remove the decimal:  8544634.120815 to -&gt; 8,544,634 ADA. 
- Any additional details: Thanks and great job on the website development! 

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 2560x1440
**[Open #85 in Usersnap](https://app.usersnap.com/l/feedback/0256cbae-4617-43b3-bdc8-4bcd922167dc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-11-04 07:56
Duplicate of #2305

**Closed by bosko-m** 2024-11-04 07:56 UTC
Labels: usersnap-feature
