### ISSUE TITLE
🐛 Unable to Register as dRep or Sole Voter

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#2355] opened 2024-11-08 06:03 UTC
### Area

Other

### Domain

preview.gov.tools

### Which wallet were you using?

Eternl Wallet v1.12.16, Lace 1.17.1, demos 1.8.2

### Context

I encountered an issue when attempting to register as a dRep and as a sole voter. Both registration attempts failed despite providing valid data.

### Steps to reproduce

1. Connect to the wallet.
2. Attempt to register as a dRep with valid data.
3. Attempt to register as a sole voter.
4. Observe the modal for any errors.

### Actual behavior

Attached screenshots show the errors observed during both registration attempts:

![Screenshot from 2024-11-08 10-41-26](https://github.com/user-attachments/assets/0848464c-4bf7-41bf-9828-1c3917f9eb1c)

![Screenshot from 2024-11-08 10-45-10](https://github.com/user-attachments/assets/60b4ea59-752c-475f-adcb-cea073463ad6)

### Expected behavior

Registration as a dRep and as a sole voter should complete successfully without errors when valid data is provided.

### Allure report 
- [2E. Should register as Direct voter](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/d0d633f124e7ecbe/)
- [2N. Should show DRep information on details page](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/77696fe1f7d28f0b/)
- [2S. Should retire as a Direct Voter on delegating to another DRep](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/e640b5e6e8584467/)
- [3G. Should show confirmation message with link to view transaction, when DRep registration txn is submitted](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/e176f5f3ce551cc5/)
- [3I. Should display 'In Progress' status on dashboard until blockchain confirms DRep registration](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/1581a8ab4a9c9bde/)
- [3Q Should not list dRep in the dRep directory when 'doNotList' is checked during registration](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/862b06e55792a2e0/)

**Comment by MSzalowski** [comment] 2024-11-08 11:34
Certs should be in correct order (drep and stake key registration before vote delegation)
Screen of the certificates before signing transaction:
![Zrzut ekranu z 2024-11-08 12-30-55](https://github.com/user-attachments/assets/65d924ac-d98f-49e0-b294-abec4f6e02d1)

And successfully signed and submitted transaction:
![Zrzut ekranu z 2024-11-08 12-31-09](https://github.com/user-attachments/assets/9550c791-f870-4893-97bc-33f2ac529773)

Also my DRep registration transaction is listed on cexplorer being submitted on chain:
https://preview.cexplorer.io/tx/41ea2ad17c8bcb78ddc8495f4cd8c3ba6e984ac4dd6b55e6bada9ba3806f2677

**Comment by MSzalowski** [comment] 2024-11-08 11:43
My retirement transaction certs:
![Zrzut ekranu z 2024-11-08 12-35-30](https://github.com/user-attachments/assets/c2a55a03-bb42-4e2b-9d09-84e4d733de02)

And after retiring I was able to once again register as a DRep:
![Zrzut ekranu z 2024-11-08 12-40-50](https://github.com/user-attachments/assets/5166ea65-afab-40d9-af21-5fc6e14cb372)

**Comment by MSzalowski** [comment] 2024-11-08 11:44
Also reregister transaction correctly didn't include stake key registration:
![Zrzut ekranu z 2024-11-08 12-44-28](https://github.com/user-attachments/assets/b5a9b500-3118-42a1-a31a-4267e2096ef4)

**Comment by MSzalowski** [comment] 2024-11-08 11:46
@kneerose Could you please verify if that is still failing for you? If so - could you please verify if version of the app (1.0.26) is correct?

Also I was testing on newer cardano-node and newer db-sync. Maybe it is caused by having the older versions on preview

**Comment by kneerose** [comment] 2024-11-11 05:47
@MSzalowski  On the development environment, both the dRep registration process and direct voter registration are functioning correctly. However, on the preview network, transactions are not being successfully submitted. I have tested with both the Eternl wallet and the Lace wallet, and each reports different errors.

Details:

- Direct voter registration via Lace wallet on the preview network (version 1.17.1):

![image](https://github.com/user-attachments/assets/83a57d94-3151-4aee-bf7c-830e8874fc14)

- Certificate order in the development environment.
 
![Screenshot from 2024-11-11 11-12-57](https://github.com/user-attachments/assets/5ff5121b-974f-45d9-931a-0699c896061e)


- Certificate order in the preview environment.

![Screenshot from 2024-11-11 11-12-39](https://github.com/user-attachments/assets/a86187fd-bbe7-4aa1-92e5-f1ddffe8b740)

These screenshots confirm that the preview environment has not been updated correctly, and the issue is still reproducible.

**Comment by MSzalowski** [comment] 2024-11-12 10:51
Then, it should be done once the deployment issue on preview is resolved @bosko-m

**Comment by bosko-m** [comment] 2024-11-12 12:01
Will be resolved with #2333

**Closed by bosko-m** 2024-11-12 12:01 UTC
Labels: 🐛 Bug, Other area
