### ISSUE TITLE
[USERSNAP] https://gov.tools/drep_directory filter doesnt find drep CryptoCrow when searching for crow

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2110] opened 2024-10-02 09:50 UTC
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Add a comment: https://gov.tools/drep_directory filter doesnt find drep CryptoCrow when searching for crow

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1920x1080
**[Open #138 in Usersnap](https://app.usersnap.com/l/feedback/85486e84-64aa-4ff2-97b3-bbcb5f482190?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jdyczka** [comment] 2024-10-02 11:58
connected to #1893

**Comment by bosko-m** [comment] 2024-10-10 11:59
Duplicate of #1893

**Closed by bosko-m** 2024-10-10 11:59 UTC
Labels: usersnap-bug
