### ISSUE TITLE
[USERSNAP] Searching for a Drep doesn't work. In order to find them you need to scroll until it appears. Added screenshots to show bug.  *The DRep updated its name about 12 hours ago.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2135] opened 2024-10-10 03:19 UTC
**Taken at**: https://gov.tools/connected/drep_directory
**Fields**:
- Add a comment: Searching for a Drep doesn&#39;t work. In order to find them you need to scroll until it appears. Added screenshots to show bug. 

*The DRep updated its name about 12 hours ago.

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 3440x1440
**[Open #143 in Usersnap](https://app.usersnap.com/l/feedback/58233ba0-a7a8-495b-abc9-8938eb177268?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-10-10 12:00
Duplicate of #1893 .

**Closed by bosko-m** 2024-10-10 12:00 UTC
Labels: usersnap-bug
