### ISSUE TITLE
[USERSNAP] The json that's automatically generated when registering as a DRep does not include the @language property under @context. This generates a metadata error when someone checks you on adastat.net Explorer.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2080] opened 2024-09-26 04:50 UTC
**Taken at**: https://gov.tools/
**Fields**:
- Add a comment: The json that&#39;s automatically generated when registering as a DRep does not include the @language property under @context. This generates a metadata error when someone checks you on adastat.net Explorer.

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1920x1080
**[Open #134 in Usersnap](https://app.usersnap.com/l/feedback/cb2113a4-0366-4875-865b-82868a9cefc7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jdyczka** [comment] 2024-10-02 12:12
This issue is connected to #1856

**Comment by bosko-m** [comment] 2024-11-04 08:44
Duplicate of #1856 .

**Closed by bosko-m** 2024-11-04 08:44 UTC
Labels: usersnap-bug
