### ISSUE TITLE
Chore: Bump DB-Sync to version `sancho-5-0-0`

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1473] opened 2024-07-04 20:31 UTC
### Why

- GovTool is currently on DB-Sync version `sancho-4-3-0` with Node version `8.11.0`
- DBSync team have [released two newer versions](https://github.com/IntersectMBO/cardano-db-sync/releases) since with `sancho-5-0-0` (node `8.11.0` compatible) and `sancho-5.1.0` (node `8.12.0` compatible).
- Soon (maybe late next week), SanchoNet will be respun to Node 8.12.0 which will force us to upgrade to `sancho-5.1.0`
  - To reduce the complexity of this at time of re-spin, I suggest we update GovTool to `sancho-5-0-0` sooner
  - As the changes from `4` to `5` are significant schema changes, if we focus on the needed backend changes now, we wont be in such a rush at time of next respin.

### What

- Bump infra configure to use DBSync `sancho-5-0-0`

### How

- Bump infra configure to use DBSync `sancho-5-0-0`

**Comment by bosko-m** [comment] 2024-07-10 09:35
@Ryun1 Do you feel #1538 is a duplicate of this task?

**Comment by Ryun1** [comment] 2024-07-12 19:33
We should now bump straight to DBSync 5.1.0, as this is compatible with Node 9.0.0 which is what SanchoNet is running on

**Comment by Ryun1** [comment] 2024-07-12 19:36
> @Ryun1 Do you feel https://github.com/IntersectMBO/govtool/issues/1538 is a duplicate of this task?

@bosko-m
No! we should probably close this ticket and just track the issue on https://github.com/IntersectMBO/govtool/issues/1538 now, as upgrading straight to 5.1.0 will be a better option

**Comment by MSzalowski** [comment] 2024-07-15 06:14
I am closing the issue then. We'll bump the db-sync straight to 5.1.0

**Closed by MSzalowski** 2024-07-15 06:14 UTC
Labels: 🏗 Infrastructure, DBSync5.0.0
