### ISSUE TITLE
[USERSNAP] After connecting my wallet I just get a spinny wheel and the page never loads.  Also a pale blue bar appears showing my network to be Preview, but clicking Main net does nothing.  I'm on a new imac with current OS and have restarted. But it s...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2207] opened 2024-10-23 20:18 UTC
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: After connecting my wallet I just get a spinny wheel and the page never loads. 
Also a pale blue bar appears showing my network to be Preview, but clicking Main net does nothing. 
I&#39;m on a new imac with current OS and have restarted. But it still won&#39;t load. 

**Browser**: Chrome 130 (macOS Catalina)
**Screen size**: 1678x875
**[Open #151 in Usersnap](https://app.usersnap.com/l/feedback/ef244824-33aa-49fc-a335-b789b33fc892?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-11-04 14:49
Duplicate of #2295 , worth investigating.

**Closed by bosko-m** 2024-11-04 14:49 UTC
Labels: usersnap-bug
