### ISSUE TITLE
[USERSNAP] Clearly name the proposer of the Governance Action

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2291] opened 2024-10-31 19:28 UTC
**Taken at**: https://gov.tools/connected/governance_actions/51f495aa23f4b3b3aa90afde4a0e67823bb7ac4ac65f5ffbb138373b863f2f74#0
**Fields**:
- Name of the idea or new feature: Clearly name the proposer of the Governance Action
- Please summarize your idea or new feature: I am reading the new Governance Action named Plutus V3 Cost Model ... It has several paragraphs mentioning &#34;We propose to update the ...&#34; The use of We made me search for the proposer of the governance action, but I cannot see who is the proposer.

Is there a way to clearly label who is the proposer of a governance action?
- Any additional details: The link to the governance action is:

https://gov.tools/connected/governance_actions/51f495aa23f4b3b3aa90afde4a0e67823bb7ac4ac65f5ffbb138373b863f2f74#0

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1712x943
**[Open #91 in Usersnap](https://app.usersnap.com/l/feedback/d4cc0888-0966-45f9-9ea9-ef513cba6c69?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-11-04 14:15
Duplicate of #2016 .

**Closed by bosko-m** 2024-11-04 14:15 UTC
Labels: usersnap-feature
