### ISSUE TITLE
[USERSNAP] It keep saying that the data does not match the json file hosted on github

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2324] opened 2024-11-04 19:22 UTC
**Taken at**: https://gov.tools/register_drep
**Fields**:
- Add a comment: It keep saying that the data does not match the json file hosted on github

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1920x1080
**[Open #159 in Usersnap](https://app.usersnap.com/l/feedback/c000617c-e842-412c-b6ce-0b80904d776f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-11-05 08:20
Duplicate of #2311 .

**Closed by bosko-m** 2024-11-05 08:20 UTC
Labels: usersnap-bug
