### ISSUE TITLE
[USERSNAP] units and alignment

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#881] opened 2024-04-27 01:34 UTC
**Taken at**: https://sanchogov.tools/connected/governance_actions/10749d25c892a6ec20fc9365425dc204c6a2699ce1586bdb0e6802eccd6263f2#0
**Fields**:
- Name of the idea or new feature: units and alignment
- Please summarize your idea or new feature: in the show votes popup where the amount of ada is shown the numbers could be aligned to the point and diferenciate the units on it. otherwise one has to be counting because it is not clear if number are thousands or millions. 

**Browser**: Chrome 124 (Linux)
**Screen size**: 1920x1080
**[Open #38 in Usersnap](https://app.usersnap.com/l/feedback/885ddc97-6d03-4fa1-98aa-786995270a9a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment] 2024-05-03 11:58
If I understand what the user is saying, they want to see better aligned voting numbers in GA action detail pages.

Here is the (new) figma design for showing votes. There is no votes past the decimal point, but there should be commas to separate the thousands.
<img width="605" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/8d5ccd05-ac4a-4ef5-8b8a-39afaa8c268e">

**Comment by m-i-k-e** [comment] 2024-05-03 11:59
I will add this to the design queue.

**Comment by m-i-k-e** [comment] 2024-05-03 11:59
@GypsyBinar Please make a version of Vote counting where there are thousands separators.

**Comment by m-i-k-e** [comment] 2024-05-13 16:14
There is a Figma branch for this file. @GypsyBinar Did you work on it? if so, please can you add a link here so I can check it?

**Comment by kgrzonka** [comment] 2024-05-16 08:17
@m-i-k-e 
https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/branch/3j2eeOxRE58qwZPeZDy3O7/Voltaire---GOV-TOOL?m=auto&node-id=8462%3A51213&t=VbSEye8CK4eCkCqh-1

**Comment by kgrzonka** [comment] 2024-05-16 11:20
@m-i-k-e and  in this case we don't need branching. I change the copy in components in Master ok?

**Comment by kgrzonka** [comment] 2024-05-17 06:31
@m-i-k-e 
https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=9420%3A158655&t=KJhF4p4O8ZBQ60yz-1

Done :)

**Comment by m-i-k-e** [comment] 2024-05-17 11:17
Thanks, @kgrzonka This looks good.

**Comment by m-i-k-e** [comment] 2024-05-17 11:17
@MSzalowski This is ready to implement

**Comment by m-i-k-e** [comment] 2024-07-18 09:59
@MSzalowski Did this get implemented?

**Comment by m-i-k-e** [comment] 2024-11-01 17:19
This is a live issue.

**Comment by bosko-m** [comment] 2024-11-03 19:48
Duplicate of #2305 .

**Closed by bosko-m** 2024-11-03 19:48 UTC
Labels: usersnap-feature, 🎨 Design Needed
