### ISSUE TITLE
[USERSNAP] My Ada balance delegated to a DRep is wrong. It says I have 33 million Ada.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2517] opened 2024-12-12 13:05 UTC
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: My Ada balance delegated to a DRep is wrong. It says I have 33 million Ada.

**Browser**: Chrome 131 (macOS Catalina)
**Screen size**: 1712x966
**[Open #175 in Usersnap](https://app.usersnap.com/l/feedback/e4939bab-7d3d-4cb8-a17d-bf75a9c0b426?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment] 2024-12-18 08:32
Duplicate of #2460

**Closed by bosko-m** 2024-12-18 08:32 UTC
Labels: usersnap-bug
