### ISSUE TITLE
[USERSNAP] Randomize the list of DReps

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2035] opened 2024-09-12 14:51 UTC
**Taken at**: https://gov.tools/connected/drep_directory
**Fields**:
- Name of the idea or new feature: Randomize the list of DReps
- Please summarize your idea or new feature: Every time I log in to the gov.tools DRep directory, I see Army of Spies as the first DRep in the list. There is a need for a randomization of the appearance order 

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1540x746
**[Open #79 in Usersnap](https://app.usersnap.com/l/feedback/443046b3-17b6-44f7-81af-c1eb25be2188?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment] 2024-09-12 15:20
@kickloop We need to look a bit deeper into how we tell the users about the sort order of the DReps. There is an issue for redesign of the list page, and this feature should go as an improvement in that issue. Why? Because it's not the only problem with that page. One big problem is that we don't show the users what the sort order is. It's impossible to discern. Can you please @ me or Lorenzo for anything that affects the user experience?

**Comment by Ryun1** [comment] 2024-09-12 16:17
I have created a milestone for all search / filter / sort related issues

**Comment by Ryun1** [comment] 2024-09-13 08:37
Duplicate of https://github.com/IntersectMBO/govtool/issues/2013

**Comment by m-i-k-e** [comment] 2024-09-20 13:18
This is live on preview. It works

**Closed by m-i-k-e** 2024-09-20 13:18 UTC
Labels: usersnap-feature, 🧬 UX, 🎨 Design Needed
